
from django.urls import path
from .import views

urlpatterns = [
    
    path('', views.index,name='index'),
    path('inicio/', views.index,name='inicio'),    
    path('registro_usuario/', views.registro_usuario,name='registro_usuario'),
    path('login/', views.login_user,name='login'),
    path('logout/', views.logout_user,name='logout'),
    path('usuarios/', views.consultar_usuarios,name='consultar_usuarios'),
    path('usuario/<int:id>', views.consulta_usuario_id,name='consulta_usuario_id'),
    path('elminar/<int:id>', views.eliminar_usuario,name='eliminar_usuario'),
    path('biometria/<int:id>', views.biometria,name='biometria'), 
    path('subir_foto/', views.subir_foto,name='subir_foto'),
    path('consultar_imagen/<int:id>/<int:idcita>', views.consultar_imagen,name='consultar_imagen'),
    path('verificar_imagen/', views.verificar_imagen,name='verificar_imagen'),
    path('consultar_pacientes/', views.consultar_pacientes,name='consultar_pacientes'),
    path('registro_paciente/', views.registro_paciente,name='registro_paciente'),
    path('eliminar_paciente/<int:id>', views.eliminar_paciente,name='eliminar_paciente'),   
    path('paciente/<int:id>', views.consulta_paciente_id,name='consulta_paciente_id'), 
    path('consultar_signosVitales/', views.consultar_signos_vitales,name='consultar_signosVitales'), 
    path('carga_Provincia/', views.carga_Provincia,name='carga_Provincia'), 
    path('carga_Ciudad/', views.carga_Ciudad,name='carga_Ciudad'), 
    path('carga_TipoSangre/', views.carga_TipoSangre,name='carga_TipoSangre'), 
    path('carga_EstadoCivil/', views.carga_EstadoCivil,name='carga_EstadoCivil'),
    path('carga_Sexo/', views.carga_Sexo,name='carga_Sexo'),
    path('carga_CiudadNac/', views.carga_CiudadNac,name='carga_CiudadNac'),
    path('consultar_pacientes_filtro/', views.consultar_pacientes_filtro,name='consultar_pacientes_filtro'),
    path('agendar_cita/<int:id>', views.agendar_cita,name='agendar_cita'),
    path('carga_horas/', views.carga_horas,name='carga_horas'),
    path('carga_doctor/', views.carga_doctor,name='carga_doctor'),
    path('consultar_paciente_citaFiltro/', views.consultar_pacientesCita_filtro,name='consultar_paciente_citaFiltro'),
    path('signos_vitales/<int:id>', views.signos_vitales,name='signos_vitales'),
    path('consultar_pacientesCita_Doc/', views.consultar_pacientesCita_Doc,name='consultar_pacientesCita_Doc'),
    path('consultar_pacientesFicha/', views.consultar_pacientesCita_Doc,name='consultar_pacientesFicha'),
    path('consulta_medica/<int:id>', views.consulta_medica,name='consulta_medica'),
    path('laboratorio/<int:id>/<int:idcons>', views.laboratorio,name='laboratorio'),
    path('carga_estudios/', views.carga_estudios,name='carga_estudios'),       
    path('carga_medicina/', views.carga_medicina,name='carga_medicina'),
    path('medicina/<int:id>/<int:idcons>', views.medicina,name='medicina'),
    path('admision_paciente/', views.admision_paciente,name='admision_paciente'),
    path('consultar_pacientes_ficha/', views.consultar_pacientes_ficha,name='consultar_pacientes_ficha'),
    path('ficha/<int:id>/<int:existeFicha>/<int:idFicha>', views.ficha,name='ficha'),      
    path('consulta_general/<int:id>/<int:idcons>', views.consulta_general,name='consulta_general'),    
    path('consulta_historial/<int:id>', views.consulta_historial,name='consulta_historial'),
    path('send/', views.postSend, name='send'),
    path('consultar_pacientes_filtro_a/', views.consultar_pacientes_filtro_a,name='consultar_pacientes_filtro_a'),    
]
