# Generated by Django 3.2.12 on 2022-03-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_persona', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('numero_identificacion', models.CharField(default='', max_length=10)),
                ('nombres', models.CharField(default='', max_length=50)),
                ('apellidos', models.CharField(default='', max_length=50)),
                ('domicilio', models.CharField(default='', max_length=120)),
                ('correo_contacto', models.CharField(default='', max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('mainapp.usuario',),
        ),
    ]
