# Generated by Django 3.2.12 on 2022-03-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
