# Generated by Django 3.2.12 on 2022-03-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_registerform'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_perfil',
            field=models.IntegerField(default='0'),
        ),
    ]
