# Generated by Django 3.2.12 on 2022-03-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id_opciones', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opciones_perfil',
            fields=[
                ('id_opciones_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('id_perfil', models.IntegerField()),
                ('id_opcion', models.IntegerField()),
            ],
        ),
    ]
