# Generated by Django 3.2.12 on 2022-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_opciones_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(default='', max_length=15)),
                ('nombre1', models.CharField(default='', max_length=50)),
                ('nombre2', models.CharField(default='', max_length=50)),
                ('apellido_paterno', models.CharField(default='', max_length=50)),
                ('apellido_materno', models.CharField(default='', max_length=50)),
                ('domicilio', models.CharField(default='', max_length=150)),
                ('correo_contacto', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
