# Generated by Django 3.2.12 on 2022-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
