# Generated by Django 3.2.12 on 2022-03-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_paciente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.BinaryField(editable = True,null=True),
        ),
    ]
