# Generated by Django 3.2.12 on 2022-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_paciente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.BinaryField(null=True),
        ),
    ]
