# Generated by Django 3.2.12 on 2022-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20220312_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoDetalle',
            fields=[
                ('id_catalogo_detalle', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_catalogo', models.IntegerField(null=True)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('id_padre', models.IntegerField(null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
