# Generated by Django 3.2.12 on 2022-03-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_catalogo_catalogodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendar_cita',
            fields=[
                ('id_cita', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_paciente', models.IntegerField(null=True)),
                ('id_doctor', models.IntegerField(null=True)),
                ('fecha_cita', models.DateField(null=True)),
                ('hora', models.IntegerField(null=True)),
                ('observacion', models.CharField(default='', max_length=150)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
