# Generated by Django 3.2.12 on 2022-03-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_signos_vitales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='F_respiratoria',
            new_name='f_cardiaca',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='f_cardica',
            new_name='f_respiratoria',
        ),
    ]
