# Generated by Django 3.2.12 on 2022-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20220319_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signos_vitales',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='oximetria',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='talla',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
