# Generated by Django 3.2.12 on 2022-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20220319_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('motivo', models.CharField(default='', max_length=1250)),
                ('sintomas_evolucion', models.CharField(default='', max_length=250)),
                ('exploracion_fisica', models.CharField(default='', max_length=250)),
                ('idpaciente', models.IntegerField(null=True)),
                ('iddoctor', models.IntegerField(null=True)),
                ('diagnostico', models.CharField(default='', max_length=250)),
                ('fecha_cita', models.DateField(null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
