# Generated by Django 3.2.12 on 2022-03-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_consulta', models.IntegerField(null=True)),
                ('id_paciente', models.IntegerField(null=True)),
                ('id_doctor', models.IntegerField(null=True)),
                ('id_medicamento', models.IntegerField(null=True)),
                ('dosis_observacion', models.CharField(default='', max_length=250)),
                ('fecha', models.DateField(null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
