# Generated by Django 3.2.12 on 2022-03-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendar_cita',
            name='admitido',
            field=models.IntegerField(default=0),
        ),
    ]
