# Generated by Django 3.2.12 on 2022-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_agendar_cita_admitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_paciente', models.IntegerField(null=True)),
                ('ante_hereditario_abuelos', models.CharField(default='', max_length=250)),
                ('ante_hereditario_padres', models.CharField(default='', max_length=250)),
                ('ante_hereditario_hermanos', models.CharField(default='', max_length=250)),
                ('ante_patologicos', models.CharField(default='', max_length=250)),
                ('id_tabaquismo', models.IntegerField(null=True)),
                ('id_alcoholismo', models.IntegerField(null=True)),
                ('alergias', models.CharField(default='', max_length=250)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
